name: ci

on: [push]
jobs:
  docker-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run:
          docker build -t takasakilab_pic2023 .
      - name: Push
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          docker tag takasakilab_pic2023 yudai0804/takasakilab_pic2023:$COMMIT_HASH
          docker tag yudai0804/takasakilab_pic2023:$COMMIT_HASH yudai0804/takasakilab_pic2023:latest
          docker push yudai0804/takasakilab_pic2023 -a


